[program:Xorg]
command=/usr/lib/xorg/Xorg :0 -noreset -nolisten tcp -logfile /var/log/Xorg.0.log -config /etc/X11/xorg.conf
stdout_logfile=/var/log/supervisor/Xorg.log
stderr_logfile=/var/log/supervisor/Xorg.err.log
priority=2
umask=000