[program:chrome]
command=/opt/.manus/.packages/scripts/check-start-chrome.sh
environment=DISPLAY=":0",TZ="UTC"
priority=999
startsecs=10
user=ubuntu
directory=/home/ubuntu
autorestart=true
stdout_logfile=/var/log/supervisor/chrome.log
stderr_logfile=/var/log/supervisor/chrome.err.log
depends_on=sandbox-runtime
stopasgroup=true
killasgroup=true
autostart=true