[program:x11vnc]
command=x11vnc -display :0 -repeat -rfbport 5900 -geometry 1280x1029 -shared -forever -alwaysshared -permitfiletransfer -noxrecord -noxfixes -noxdamage -dpms -desktop "chrome" -noshm
startsecs=0
autorestart=unexpected
stderr_logfile=/var/log/supervisor/x11vnc.err.log
stdout_logfile=/var/log/supervisor/x11vnc.log
depends_on=sandbox-runtime
