[program:websockify-go]
command=/opt/.manus/.packages/scripts/start-vnc.sh
user=root
stderr_logfile=/var/log/supervisor/websockify.err.log
stdout_logfile=/var/log/supervisor/websockify.log
exitcodes=0
startsecs=0
depends_on=sandbox-runtime
