[program:code-server]
command=/opt/.manus/.packages/scripts/check-start-code-server.sh
directory=/home/ubuntu
user=root
stderr_logfile=/var/log/supervisor/code-server.err.log
stdout_logfile=/var/log/supervisor/code-server.log
exitcodes=0
startsecs=0
depends_on=sandbox-runtime
autostart=false
